### ISSUE TITLE
hey man

### ISSUE THREAD

**Issue by szcs0** [szumielxd/MirrorSkull#1]
It isnt actually about MirrorSkull (but it is cool). its actually about TuSKe, Skript has released 2.6 fixed could you update TuSKe it would be **GREAT** Help! please....

Thanks for the time!

**Comment by szumielxd** [comment]
Done: <https://github.com/szumielxd/TuSKe/releases/tag/v1.10.0>
Any future issues you can create in [TuSKe-related section](https://github.com/szumielxd/TuSKe/issues)
